In [11]:
import nltk
import pandas as pd

In [55]:
twt_df = pd.read_csv('emozi_features.csv')

In [28]:
from textblob import TextBlob

In [60]:
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.

True

In [63]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\admin\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.

True

In [56]:
twt_sent = []
emozi_sent = []
for index,row in twt_df.iterrows():
    tb = TextBlob(str(row['tweet']))
    twt_sent.append(tb.sentiment.polarity)
    emozi_sent.append(2*row['aggregated_score']-1)

In [57]:
twt_df['tweet_sentiment']=twt_sent
twt_df['emozi_sentiment'] = emozi_sent

In [58]:
twt_df=twt_df.drop(twt_df.columns[[0]], axis=1)
twt_df.head(10)

,user_id,tweet id,tweet,emozi_count,emozi_description,emozi_scores,aggregated_score,tweet_sentiment,emozi_sentiment
0,1182851.0,1.072800e+18,RT @btsdanisharmy: The boys doing their thing ...,2,"['Face With Tears of Joy', 'Face With Tears of...","[0.99, 0.99]",1.00,0.625000,1.00
1,6870172.0,1.072799e+18,RT @Harem_sa: If you sharing a birthday with t...,1,['Smiling Face With Heart-Eyes'],[0.84],0.84,0.557813,0.68
2,14653803.0,1.072799e+18,RT @ErlianaShofia: Wanna one üòç\r\n#MAMAVOTE #...,1,['Smiling Face With Heart-Eyes'],[0.84],0.84,0.000000,0.68
3,15162264.0,1.072798e+18,RT @jeonggukpics: Jungkook you are just illega...,1,['Smiling Face With Heart-Eyes'],[0.84],0.84,-0.500000,0.68
4,16043942.0,1.072799e+18,RT @1K_Younginn: Internet Capp üî•Drop Or Not ? ...,1,['Fire emozi'],[0.6],0.60,0.000000,0.20
5,17383566.0,1.072800e+18,RT @prince__danik: THIS COVER IS SO üî•üî•üî•üî•\r\n\r...,8,"['Fire emozi', 'Fire emozi', 'Fire emozi', 'Fi...","[0.6, 0.6, 0.6, 0.6, 0.1, 0.1, 0.1, 0.1]",0.55,0.000000,0.10
6,17720465.0,1.072799e+18,And there's a twist here.... Watch the video n...,1,['Face With Tears of Joy'],[0.99],0.99,0.000000,0.98
7,18185282.0,1.072799e+18,RT @BTSARMY_Salon: #MAMAVOTE #BTS @BTS_twt Let...,7,"['Fire emozi', 'Fire emozi', 'Fire emozi', 'Fi...","[0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6]",0.70,0.000000,0.40
8,18940422.0,1.072798e+18,RT @MTV: Have you ever seen anything cuter????...,1,['Two Hearts'],[0.8],0.80,0.000000,0.60
9,19970375.0,1.072799e+18,RT @kittieieie: I love JAPAN üò≠ https://t.co/Vx...,1,['Loudly Crying Face'],[0.1],0.10,0.500000,-0.80

In [92]:
model_df = pd.read_csv('user_and_content_based_features.csv')

In [93]:
model_df=model_df.drop(model_df.columns[[0]], axis=1)
model_df.head(10)

,user_id,count of tweets with @,count of tweets with links,count of tweets with hashtags,reputation of user,is_spam
0,678033.0,24,5,9,0.794981,0
1,722623.0,20,5,15,0.699335,0
2,755116.0,11,11,6,0.540799,0
3,755746.0,13,8,8,0.732700,0
4,785080.0,16,0,1,0.597961,0
5,806585.0,29,2,1,0.452922,0
6,806975.0,15,6,10,0.943343,0
7,887281.0,15,3,8,0.440299,0
8,1382561.0,26,3,4,0.218849,0
9,1813221.0,17,5,0,0.569385,0

In [37]:
from sklearn.cross_validation import train_test_split 
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

C:\Users\admin\Anaconda31\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [38]:
X = model_df.iloc[:, [1,2,3,4]].values
y = model_df.iloc[:, 5].values

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.36, random_state = 21)

In [40]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
clf = SVC(kernel = 'rbf',C=90.0)
clf.fit(X_train, y_train)

SVC(C=90.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [42]:
twt_data = pd.read_csv('live_content_based_features.csv')
twt_data=twt_data.drop(twt_data.columns[[0]], axis=1)
twt_data.head()

,user_id,count of tweets with @,count of tweets with links,count of tweets with hashtags,reputation of user
0,801163.0,1,1,0,0.425595
1,1182851.0,1,0,0,0.361780
2,3241081.0,0,0,0,0.632197
3,6020572.0,2,0,3,0.966525
4,6870172.0,2,0,0,0.606225

In [43]:
x_test_twt = twt_data.iloc[: , [1,2,3,4]].values

In [44]:
y_test_twt = clf.predict(x_test_twt)

In [45]:
y_test_twt

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [49]:
label = list(y_test_twt)

In [53]:
twt_final_df = pd.DataFrame(
    {'user_id':twt_data['user_id'] ,
     'is_spam' : label
    })

In [60]:
twt_final_df.head()

     user_id  is_spam
0   801163.0        0
1  1182851.0        0
2  3241081.0        1
3  6020572.0        0
4  6870172.0        0

In [63]:
df= pd.merge(twt_df, twt_final_df, on='user_id', how='inner')

In [75]:
df.head(25)

,user_id,tweet id,tweet,emozi_count,emozi_description,emozi_scores,aggregated_score,tweet_sentiment,emozi_sentiment,is_spam
0,1182851.0,1.072800e+18,RT @btsdanisharmy: The boys doing their thing ...,2,"['Face With Tears of Joy', 'Face With Tears of...","[0.99, 0.99]",1.00,0.625000,1.00,0
1,6870172.0,1.072799e+18,RT @Harem_sa: If you sharing a birthday with t...,1,['Smiling Face With Heart-Eyes'],[0.84],0.84,0.557813,0.68,0
2,14653803.0,1.072799e+18,RT @ErlianaShofia: Wanna one üòç\r\n#MAMAVOTE #...,1,['Smiling Face With Heart-Eyes'],[0.84],0.84,0.000000,0.68,0
3,15162264.0,1.072798e+18,RT @jeonggukpics: Jungkook you are just illega...,1,['Smiling Face With Heart-Eyes'],[0.84],0.84,-0.500000,0.68,0
4,15162264.0,1.072798e+18,RT @jeonggukpics: Jungkook you are just illega...,1,['Smiling Face With Heart-Eyes'],[0.84],0.84,-0.500000,0.68,0
5,16043942.0,1.072799e+18,RT @1K_Younginn: Internet Capp üî•Drop Or Not ? ...,1,['Fire emozi'],[0.6],0.60,0.000000,0.20,0
6,17383566.0,1.072800e+18,RT @prince__danik: THIS COVER IS SO üî•üî•üî•üî•\r\n\r...,8,"['Fire emozi', 'Fire emozi', 'Fire emozi', 'Fi...","[0.6, 0.6, 0.6, 0.6, 0.1, 0.1, 0.1, 0.1]",0.55,0.000000,0.10,0
7,17720465.0,1.072799e+18,And there's a twist here.... Watch the video n...,1,['Face With Tears of Joy'],[0.99],0.99,0.000000,0.98,0
8,18185282.0,1.072799e+18,RT @BTSARMY_Salon: #MAMAVOTE #BTS @BTS_twt Let...,7,"['Fire emozi', 'Fire emozi', 'Fire emozi', 'Fi...","[0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6]",0.70,0.000000,0.40,0
9,18940422.0,1.072798e+18,RT @MTV: Have you ever seen anything cuter????...,1,['Two Hearts'],[0.8],0.80,0.000000,0.60,0
10,19970375.0,1.072799e+18,RT @kittieieie: I love JAPAN üò≠ https://t.co/Vx...,1,['Loudly Crying Face'],[0.1],0.10,0.500000,-0.80,0
11,21154134.0,1.072799e+18,RT @endclothing: The Ten: @nike x @OffWht Air ...,1,['Fire emozi'],[0.6],0.60,0.250000,0.20,0
12,21584435.0,1.072800e+18,"RT @Ek_Jacquelyn: When they said ""... Turn on ...",3,"['Face With Tears of Joy', 'Face With Tears of...","[0.99, 0.99, 0.6]",0.96,0.600000,0.92,0
13,21797682.0,1.072799e+18,RT @BabyBird9394: MY MEN üò≠üò≠üò≠üò≠ #MAMAVOTE #GOT7 ...,4,"['Loudly Crying Face', 'Loudly Crying Face', '...","[0.1, 0.1, 0.1, 0.1]",0.20,0.000000,-0.60,0
14,22962562.0,1.072799e+18,RT @CB97Stay: #StrayKids cover EXO - Overdose+...,8,"['Loudly Crying Face', 'Loudly Crying Face', '...","[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]",0.20,0.000000,-0.60,0
15,25569355.0,1.072800e+18,RT @happypilldaniel: Please vote for Wanna One...,1,['Loudly Crying Face'],[0.1],0.10,0.000000,-0.80,0
16,26396867.0,1.072799e+18,@Bilalsaeedmusic wishing you a Very very Happ...,3,"['Face Throwing a Kiss', 'Face Throwing a Kiss...","[0.88, 0.88, 0.88]",0.98,0.750000,0.96,0
17,27514348.0,1.072799e+18,RT @flirtaeguk: LOOK AT THIS BEAUTY üò©üåπ\r\n\r\n...,1,['Weary Face'],[0.35],0.35,0.000000,-0.30,0
18,28343838.0,1.072799e+18,RT @danielmarven: That's my granny for you üòÇüòÇüòÇ...,5,"['Face With Tears of Joy', 'Face With Tears of...","[0.99, 0.99, 0.99, 0.99, 0.99]",1.00,0.000000,1.00,0
19,28849589.0,1.072799e+18,RT @btsdanisharmy: The boys doing their thing ...,2,"['Face With Tears of Joy', 'Face With Tears of...","[0.99, 0.99]",1.00,0.625000,1.00,0
20,29865354.0,1.072800e+18,My Setup üòÇ #MAMAVOTE #BTS #2018MAMA https://t....,1,['Face With Tears of Joy'],[0.99],0.99,0.000000,0.98,0
21,30830367.0,1.072799e+18,RT @flirtaeguk: LOOK AT THIS BEAUTY üò©üåπ\r\n\r\n...,1,['Weary Face'],[0.35],0.35,0.000000,-0.30,0
22,30830367.0,1.072799e+18,RT @flirtaeguk: LOOK AT THIS BEAUTY üò©üåπ\r\n\r\n...,1,['Weary Face'],[0.35],0.35,0.000000,-0.30,0
23,32052180.0,1.072799e+18,RT @ElleMcbroom_: SLIME! üòÇ https://t.co/Yi32fa...,1,['Face With Tears of Joy'],[0.99],0.99,0.000000,0.98,0
24,33085946.0,1.072800e+18,This makes me sick to my stomach üòîüò§,1,['Face With Look of Triumph'],[0.2],0.20,-0.714286,-0.60,1

In [83]:
sentiment_df = []
for index,row in twt_df.iterrows():
    sentiment_df.append(abs(row['tweet_sentiment']-row['emozi_sentiment']))
    
df2 = pd.DataFrame(
    {'user_id':list(twt_df['user_id']) ,
     'sentiment_difference' : sentiment_df
    })

In [90]:
final_df= pd.merge(twt_data, df2, on='user_id', how='inner')
final_df.head()
final_df = pd.merge(twt_final_df,final_df,on='user_id',how='inner')
final_df.head(50)

,user_id,is_spam,count of tweets with @,count of tweets with links,count of tweets with hashtags,reputation of user,sentiment_difference
0,1182851.0,0,1,0,0,0.361780,0.375000
1,6870172.0,0,2,0,0,0.606225,0.122187
2,14653803.0,0,1,0,2,0.369231,0.680000
3,15162264.0,0,1,0,3,0.238518,1.180000
4,15162264.0,0,1,0,3,0.238518,1.180000
5,15162264.0,0,1,0,3,0.238518,1.180000
6,15162264.0,0,1,0,3,0.238518,1.180000
7,16043942.0,0,1,0,0,0.500000,0.200000
8,17383566.0,0,1,0,2,0.467184,0.100000
9,17720465.0,0,2,0,1,0.945096,0.980000
10,18185282.0,0,2,0,2,0.498547,0.400000
11,18940422.0,0,2,0,0,0.390041,0.600000
12,19970375.0,0,1,0,0,0.646076,1.300000
13,21154134.0,0,3,0,2,0.745223,0.050000
14,21584435.0,0,1,0,0,0.651007,0.320000
15,21797682.0,0,1,0,2,0.286989,0.600000
16,22962562.0,0,1,0,2,0.169593,0.600000
17,25569355.0,0,1,0,2,0.278788,0.800000
18,26396867.0,0,1,0,0,0.485075,0.210000
19,27514348.0,0,1,0,2,0.514289,0.300000
20,28343838.0,0,1,0,0,0.240086,1.000000
21,28849589.0,0,1,0,0,0.820843,0.375000
22,29865354.0,0,0,0,3,0.627054,0.980000
23,30830367.0,0,1,0,2,0.194365,0.300000
24,30830367.0,0,1,0,2,0.194365,0.300000
25,30830367.0,0,1,0,2,0.194365,0.300000
26,30830367.0,0,1,0,2,0.194365,0.300000
27,32052180.0,0,1,0,0,0.532670,0.980000
28,33085946.0,1,0,0,0,0.230769,0.114286
29,41331552.0,0,2,0,0,0.512839,0.800000
30,44856596.0,1,0,0,0,0.508350,0.780000
31,44856596.0,1,0,0,0,0.508350,0.780000
32,44856596.0,1,0,0,0,0.508350,0.780000
33,44856596.0,1,0,0,0,0.508350,0.780000
34,44856596.0,1,0,0,0,0.508350,0.780000
35,44856596.0,1,0,0,0,0.508350,0.780000
36,44856596.0,1,0,0,0,0.508350,0.780000
37,44856596.0,1,0,0,0,0.508350,0.780000
38,44856596.0,1,0,0,0,0.508350,0.780000
39,45133406.0,0,2,0,7,0.038095,0.800000
40,46312114.0,0,2,1,0,0.692308,0.144444
41,46312114.0,0,2,1,0,0.692308,0.144444
42,46312114.0,0,2,1,0,0.692308,0.144444
43,46312114.0,0,2,1,0,0.692308,0.144444
44,46761607.0,0,1,0,0,0.764405,0.975000
45,50723371.0,0,2,0,2,0.468672,0.491667
46,51746243.0,0,3,0,6,0.202264,0.015000
47,55186601.0,0,1,0,0,0.999401,1.155556
48,57517114.0,0,1,0,2,0.169811,0.800000
49,57714011.0,0,1,0,3,0.243564,0.680000

In [85]:
X = final_df.iloc[:, [2,3,4,5,6]].values
y = final_df.iloc[:, 1].values

In [86]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.36, random_state = 21)

In [87]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
clf = SVC(kernel = 'rbf',C=90.0)
clf.fit(X_train, y_train)

SVC(C=90.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [88]:
print ("Testing Accuracy for svm is : ",accuracy_score(y_test,clf.predict(X_test)))
print ("Training Accuracy for svm is : ",accuracy_score(y_train,clf.predict(X_train)))

Testing Accuracy for svm is :  0.9894179894179894
Training Accuracy for svm is :  1.0