# Fetching tweets using API

In [170]:
from tweepy.streaming import StreamListener
from tweepy import OAuthHandler
from tweepy import Stream

#Variables that contains the user credentials to access Twitter API 

access_token = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
access_token_secret = "xxxxxxxxxxxxxxxxxxxxxxxxx"
consumer_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
consumer_secret = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"


class StdOutListener(StreamListener):

    def on_data(self, data):
        print (data, file=open("output1.txt", "a"))
        return True

    def on_error(self, status):
        print (status, file=open("output1.txt", "a"))


if __name__ == '__main__':

    #This handles Twitter authetification and the connection to Twitter Streaming API
    l = StdOutListener()
    auth = OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)
    stream = Stream(auth, l)

    #This line filter Twitter Streams to capture data by the keywords: 
    stream.filter(track=['#', 'http',  'https'])

KeyboardInterrupt:

In [131]:
import json
import pandas as pd
import matplotlib.pyplot as plt

In [171]:
tweets_data_path = 'output1.txt'

tweets_data = []
tweets_file = open(tweets_data_path, "r")
for line in tweets_file:
    try:
        tweet = json.loads(line)
        tweets_data.append(tweet)
    except:
        continue

In [172]:
print (len(tweets_data))

72827

In [173]:
tweets = pd.DataFrame(tweets_data)

# Segregating english tweets from the corpus

In [174]:
df1=tweets

In [175]:
df2 = df1[df1.lang == 'en']

In [176]:
len(df2)

18912

In [177]:
df2.head()

,contributors,coordinates,created_at,display_text_range,entities,extended_entities,extended_tweet,favorite_count,favorited,filter_level,...,reply_count,retweet_count,retweeted,retweeted_status,source,text,timestamp_ms,truncated,user,withheld_in_countries
0,NaN,None,Wed Dec 12 10:20:52 +0000 2018,NaN,"{'hashtags': [], 'urls': [{'url': 'https://t.c...",NaN,"{'full_text': ''Mitron, who's the Pappu now?' ...",0.0,False,low,...,0.0,0.0,False,NaN,"<a href=""http://twitter.com/download/iphone"" r...","'Mitron, who's the Pappu now?' to 'Talk to the...",1544610052482,True,"{'id': 919215904424058882, 'id_str': '91921590...",NaN
2,NaN,None,Wed Dec 12 10:20:52 +0000 2018,NaN,"{'hashtags': [], 'urls': [], 'user_mentions': ...",NaN,NaN,0.0,False,low,...,0.0,0.0,False,{'created_at': 'Wed Dec 12 06:07:36 +0000 2018...,"<a href=""http://twitter.com/download/android"" ...",RT @ANI: Shivraj Singh Chouhan: Ab mein mukt h...,1544610052527,False,"{'id': 401382606, 'id_str': '401382606', 'name...",NaN
4,NaN,None,Wed Dec 12 10:20:52 +0000 2018,NaN,"{'hashtags': [], 'urls': [], 'user_mentions': ...","{'media': [{'id': 1072545061253074947, 'id_str...",NaN,0.0,False,low,...,0.0,0.0,False,{'created_at': 'Wed Dec 12 00:00:00 +0000 2018...,"<a href=""http://twitter.com/download/android"" ...",RT @MTV: Have you ever seen anything cuter????...,1544610052536,False,"{'id': 517245728, 'id_str': '517245728', 'name...",NaN
6,NaN,None,Wed Dec 12 10:20:52 +0000 2018,"[0, 140]","{'hashtags': [], 'urls': [{'url': 'https://t.c...",NaN,{'full_text': '2020 VW Passat: New Where You C...,0.0,False,low,...,0.0,0.0,False,NaN,"<a href=""https://www.autonewssite.com"" rel=""no...","2020 VW Passat: New Where You Can See, Carry-O...",1544610052234,True,"{'id': 968592364498337792, 'id_str': '96859236...",NaN
11,NaN,None,Wed Dec 12 10:20:52 +0000 2018,NaN,"{'hashtags': [{'text': 'infosec', 'indices': [...",NaN,NaN,0.0,False,low,...,0.0,0.0,False,NaN,"<a href=""https://paper.li"" rel=""nofollow"">Pape...",FASTFIRE Daily Paper is out! https://t.co/IvE9...,1544610052493,False,"{'id': 18940422, 'id_str': '18940422', 'name':...",NaN

In [178]:
text = df2['text']

In [83]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1727 entries, 0 to 2297
Data columns (total 37 columns):
contributors                 0 non-null object
coordinates                  1 non-null object
created_at                   1727 non-null object
display_text_range           231 non-null object
entities                     1727 non-null object
extended_entities            51 non-null object
extended_tweet               323 non-null object
favorite_count               1727 non-null int64
favorited                    1727 non-null bool
filter_level                 1727 non-null object
geo                          1 non-null object
id                           1727 non-null int64
id_str                       1727 non-null object
in_reply_to_screen_name      209 non-null object
in_reply_to_status_id        203 non-null float64
in_reply_to_status_id_str    203 non-null object
in_reply_to_user_id          209 non-null float64
in_reply_to_user_id_str      209 non-null object
is_quote_status              1727 non-null bool
lang                         1727 non-null object
place                        18 non-null object
possibly_sensitive           315 non-null object
quote_count                  1727 non-null int64
quoted_status                367 non-null object
quoted_status_id             367 non-null float64
quoted_status_id_str         367 non-null object
quoted_status_permalink      367 non-null object
reply_count                  1727 non-null int64
retweet_count                1727 non-null int64
retweeted                    1727 non-null bool
retweeted_status             1208 non-null object
source                       1727 non-null object
text                         1727 non-null object
timestamp_ms                 1727 non-null object
truncated                    1727 non-null bool
user                         1727 non-null object
withheld_in_countries        3 non-null object
dtypes: bool(4), float64(3), int64(5), object(25)
memory usage: 465.5+ KB

In [15]:
df2.head()

,contributors,coordinates,created_at,display_text_range,entities,extended_entities,extended_tweet,favorite_count,favorited,filter_level,...,reply_count,retweet_count,retweeted,retweeted_status,source,text,timestamp_ms,truncated,user,withheld_in_countries
0,None,None,Sun Nov 25 10:52:46 +0000 2018,NaN,"{'hashtags': [], 'urls': [], 'user_mentions': ...",NaN,NaN,0,False,low,...,0,0,False,{'created_at': 'Sun Nov 25 02:10:49 +0000 2018...,"<a href=""http://twitter.com/download/android"" ...",RT @RealMattCouch: ⚠Happy Saturday Night Patri...,1543143166489,False,"{'id': 14421994, 'id_str': '14421994', 'name':...",NaN
1,None,None,Sun Nov 25 10:52:46 +0000 2018,"[23, 140]","{'hashtags': [], 'urls': [{'url': 'https://t.c...",NaN,{'full_text': '@CaveTamasin @kmqkatie This pro...,0,False,low,...,0,0,False,NaN,"<a href=""http://twitter.com"" rel=""nofollow"">Tw...",@CaveTamasin @kmqkatie This process is like sl...,1543143166477,True,"{'id': 497126517, 'id_str': '497126517', 'name...",NaN
2,None,None,Sun Nov 25 10:52:46 +0000 2018,NaN,"{'hashtags': [{'text': 'Afghanistan', 'indices...",NaN,NaN,0,False,low,...,0,0,False,{'created_at': 'Sun Nov 25 10:51:32 +0000 2018...,"<a href=""http://twitter.com/download/android"" ...",RT @LotteLeicht1: Int'l donors should understa...,1543143166954,False,"{'id': 227535569, 'id_str': '227535569', 'name...",NaN
5,None,None,Sun Nov 25 10:52:48 +0000 2018,NaN,"{'hashtags': [{'text': 'Iran', 'indices': [109...",NaN,{'full_text': 'Iran Continues Its Attacks on O...,0,False,low,...,0,0,False,NaN,"<a href=""http://twitter.com"" rel=""nofollow"">Tw...",Iran Continues Its Attacks on Organized Opposi...,1543143168524,True,"{'id': 292418900, 'id_str': '292418900', 'name...",NaN
8,None,None,Sun Nov 25 10:52:50 +0000 2018,NaN,"{'hashtags': [], 'urls': [{'url': 'https://t.c...",NaN,{'full_text': 'You obviously mean scumbags get...,0,False,low,...,0,0,False,NaN,"<a href=""http://twitter.com"" rel=""nofollow"">Tw...",You obviously mean scumbags getting their just...,1543143170487,True,"{'id': 958418334436986880, 'id_str': '95841833...",NaN

In [179]:
df = list(df2['user'])

In [180]:
users = pd.DataFrame(df)

In [181]:
users.head()

,contributors_enabled,created_at,default_profile,default_profile_image,description,favourites_count,follow_request_sent,followers_count,following,friends_count,...,profile_text_color,profile_use_background_image,protected,screen_name,statuses_count,time_zone,translator_type,url,utc_offset,verified
0,False,Sat Oct 14 14:58:44 +0000 2017,True,False,yathā rājā tathā prajā,108,None,104,None,1286,...,333333,True,False,VinuLive,4661,None,none,http://www.vinuabraham.com,None,False
1,False,Sun Oct 30 13:23:41 +0000 2011,True,False,I don’t ask for much. Just promise you will st...,6895,None,80,None,1742,...,333333,True,False,sahil_mansoori,1994,None,none,http://www.facebook.com,None,False
2,False,Wed Mar 07 05:29:39 +0000 2012,False,False,"➳ Cʀᴇᴏ ᴇɴ ᴍɪ́ ᴍɪsᴍᴏ ᴅᴇɴᴛʀᴏ ᴅᴇ ᴇsᴛᴇ ʟᴀʙᴇʀɪɴᴛᴏ, ...",54325,None,301,None,1711,...,333333,True,False,AleTaeTae,8445,None,none,None,None,False
3,False,Tue Feb 27 21:03:10 +0000 2018,True,False,None,0,None,66,None,50,...,333333,True,False,autonewssiite,14082,None,none,None,None,False
4,False,Tue Jan 13 15:12:32 +0000 2009,True,False,"Co-Founder & Senior Security Manager at SEC4U,...",494,None,188,None,294,...,333333,True,False,fastfire,4374,None,none,http://www.fastfire.org,None,False

In [182]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18912 entries, 0 to 18911
Data columns (total 39 columns):
contributors_enabled                  18912 non-null bool
created_at                            18912 non-null object
default_profile                       18912 non-null bool
default_profile_image                 18912 non-null bool
description                           15768 non-null object
favourites_count                      18912 non-null int64
follow_request_sent                   0 non-null object
followers_count                       18912 non-null int64
following                             0 non-null object
friends_count                         18912 non-null int64
geo_enabled                           18912 non-null bool
id                                    18912 non-null int64
id_str                                18912 non-null object
is_translator                         18912 non-null bool
lang                                  18912 non-null object
listed_count                          18912 non-null int64
location                              12286 non-null object
name                                  18912 non-null object
notifications                         0 non-null object
profile_background_color              18912 non-null object
profile_background_image_url          18912 non-null object
profile_background_image_url_https    18912 non-null object
profile_background_tile               18912 non-null bool
profile_banner_url                    16497 non-null object
profile_image_url                     18912 non-null object
profile_image_url_https               18912 non-null object
profile_link_color                    18912 non-null object
profile_sidebar_border_color          18912 non-null object
profile_sidebar_fill_color            18912 non-null object
profile_text_color                    18912 non-null object
profile_use_background_image          18912 non-null bool
protected                             18912 non-null bool
screen_name                           18912 non-null object
statuses_count                        18912 non-null int64
time_zone                             0 non-null object
translator_type                       18912 non-null object
url                                   4897 non-null object
utc_offset                            0 non-null object
verified                              18912 non-null bool
dtypes: bool(9), int64(6), object(24)
memory usage: 4.5+ MB

In [183]:
tweets = df2

## Calculating content based feature for the extracted data

In [184]:
data_df = users[pd.notnull(users['followers_count'])]

In [187]:
user_followers = list(data_df['followers_count'])
user_friends = list(data_df['friends_count'])
j = 0
l = []
for i in range(len(user_friends)):
    if((user_friends[i]+user_followers[i])==0):
        print (i)
        l.append(i)

In [186]:
# data_df=data_df.drop(data_df.index[759])
#for x in l:
#    data_df=data_df.drop(data_df.index[x-j])
#    j=j+1

In [188]:
reputation = [0 for x in range(len(data_df))]
i = 0
y = 0 
f = 0
#y_actual = data_df['isfake']
#y_actual =list(y_actual)
for i in range(len(reputation)):
  #  if(user_friends[i]>user_follows[i] * 5):
    reputation[i]= user_followers[i]/(user_friends[i]+user_followers[i])
    i=i+1
print(reputation[0:10])

[0.07482014388489208, 0.043907793633369926, 0.1496023856858847, 0.5689655172413793, 0.3900414937759336, 0.34230685051433574, 0.2972593113141251, 0.592964824120603, 0.18001885014137606, 0.6956521739130435]

In [189]:
unique_ids = data_df['id']
len(unique_ids)

18833

In [190]:
final_df = pd.DataFrame(
    {'user_id': unique_ids,
     'reputation of user': reputation
    })
final_df

                   user_id  reputation of user
0       919215904424058882            0.074820
1                401382606            0.043908
2                517245728            0.149602
3       968592364498337792            0.568966
4                 18940422            0.390041
5                 43754725            0.342307
6                135864208            0.297259
7                701659766            0.592965
8                 72271239            0.180019
9      1049655381520134144            0.695652
10      996074753793384448            0.207547
11      842618329546330112            0.502508
12              3240806855            0.916599
13      938340120398258177            0.044304
14     1026352253525848069            0.705734
15      849538302575333376            0.880952
16      889444837585428480            0.205714
17      755801049903104000            0.716507
18      935536536438919175            0.555882
19     1056550139907559424            0.430082
20     1032638950588862465            0.100877
21      849320922876084224            0.660900
22     1028128541127323648            0.464198
23      736921759128137730            0.050000
24                68625975            0.880851
25               200053114            0.171053
26      809770946508636161            0.000000
27      841030495320342529            0.491935
28      761432009805733888            0.110188
29               886549045            0.139130
...                    ...                 ...
18882   889729882850181120            0.229508
18883   796365860105383936            0.819620
18884   925762172793380866            0.379032
18885  1038643311769075712            0.509356
18886            328440716            0.632563
18887            272093380            0.433806
18888   757560013061705728            0.386760
18889           3248627990            0.913317
18890            938783888            0.314815
18891   793148148881448960            0.267887
18892   892978839210647553            0.570175
18893   947611825264140288            0.015385
18894  1059244810635239424            0.277778
18895  1058852405381451776            0.502488
18896   935188265430380544            0.059748
18897            287326874            0.366833
18898   992401594166624256            0.029070
18899             62794784            0.904423
18900   765027273581924355            0.844444
18901   969162088395493376            0.142534
18902            366112267            0.565957
18903            147129919            0.689502
18904           3301718391            0.152290
18905  1014261731541938176            0.237500
18906   947072342546554880            0.320000
18907             23269580            0.525921
18908   904696382925168640            0.261538
18909            993967026            0.403922
18910   877554440999321601            0.160142
18911            170378065            0.503972

[18833 rows x 2 columns]

In [191]:
final_df = final_df.sort_values(by=['user_id'])

# Calculating content based feature

In [192]:
df1 = df2

In [193]:
df1['user']=users['id']

In [195]:
df1 = df1[pd.notnull(df1['user'])]
print(len(df1))
unique_ids =  list(set(list(df1['user'])))
print(len(unique_ids))

4963
4831

In [196]:
df1 = df1.sort_values(by=['user'])

In [203]:
df1['text']

4115     RT @J1HOON: i see no difference https://t.co/i...
16712    RT @btsdanisharmy: The boys doing their thing ...
2171     Media Speaks: Flag off (Hausla Cancer Awarenes...
1763     RT @Taepics95: 🐯: “and we’ll dance very... ver...
10032    RT @Harem_sa: If you sharing a birthday with t...
7472     RT @KShostakovskaya: ❄️🌲❄️🌲🦌🌲HAVE A NICE DAY🎄❄...
3640     RT @taehyungsrarity: question: does jung hoseo...
9049     RT @byunbaekgif: [NOTICE] Hi! This is @byunbae...
15178    RT @caldwelljunior: Loved this series so much ...
8275     RT @weareoneEXO: EXO 엑소 The 5th Full Album Rep...
16204    RT @steven_winstone: Pay attention:\n\nArlene ...
988      RT @ErlianaShofia: Wanna one  😍\n#MAMAVOTE #wa...
5198     Owwwwww...  Can't wait for @coinbase to go bel...
10636    RT @Onigiri_Omurice: Daniel performing in suit...
622      RT @jeonggukpics: Jungkook you are just illega...
14640    RT @blue_sky2509: 🌼⛅🌤️  Beautiful view .... af...
4572     RT @GOT7_JYP: GOT7 is announced as one of the ...
5420     ME RIGHT NOW\n#MAMAVOTE #WANNAONE \n@WannaOne_...
3401     RT @btsvotingteam: Twitter hashtag voting for ...
4597     RT @PuneethRajkumar: Happy Birthday to my all ...
1786     RT @always4iKON: @theseoulstory @kalachoochii ...
3919     RT @stussyjimin: BTS Worldwide MAMA top 10 cut...
12336    RT @1K_Younginn: Internet Capp 🔥Drop Or Not ? ...
8147     OHMYGOD MY HEART IS TOO WEAK FOR THIS https://...
7376     RT @chamwink: to kang daniel❤️\n\ndaniel who w...
15335    RT @billybragg: This has gone straight to the ...
9358     RT @jintaellect: This is what happens when the...
352      RT @BakwasNaKaroo: Go Ready To Win #SuzukiPaki...
6187     RT @AndrewChesnut1: Brazil police to investiga...
17705    RT @prince__danik: THIS COVER IS SO 🔥🔥🔥🔥\n\n😭😭...
                               ...
6456     RT @misayeon: TWICE won Worldwide Fans’ Choice...
1602     RT @mnchldrm: CONGRATS KINGS #MAMAVOTE #BTS @B...
2200     RT @JIMlNSTOPLIP: i still can’t believe this i...
15606    RT @TamilCensor: BREAKING NEWS \n\n#Thalapathy...
15851    RT @mygsmoonlight: jins just out here living h...
10141    RT @GARATSmeanie: 181212 Samuel in the red car...
10416    RT @EXOGlobal: [OFFICIAL] 181212 naturerepubli...
10966    RT @MnetMAMA: [#2018MAMA FANS' CHOICE in JAPAN...
15493    RT @HuynHong18: #MAMAVOTE #BTS \nFighting http...
6467     RT @btsvotingteam: Twitter hashtag voting for ...
16786                                            wanna one
6003     RT @SpotifyKDaebak: How does #TheyearofYES mak...
12359    RT @odarteii: Shutdown💥@IamKingPromise 15th DE...
8589     RT @w_terrence: CRYING CHUCK SCHUMER said Trum...
7846      That would be a hard no. https://t.co/QLBxOPmUgg
12884    RT @OfficialMwave: [#LIVE #2018MAMA ] Congratu...
2325     RT @0u0pp: #MAMAVOTE #wannaone\n\n2018 MAMA in...
3324     RT @RTUKnews: UPDATE: @theresa_may is expected...
16100             He's back. #Lolo https://t.co/f8Eg6Vmurb
5803     RT @janerichsen: 6,5 m million views without c...
13321    RT @3shells1991: “I heard our agency is suing ...
6687     RT @BTS_National: 181212 [PRESS] @BTS_twt at M...
14125    RT @GOT7_JYP: #MAMAVOTE #GOT7\n\nAhgases! It's...
14128    RT @XCXBIX: aren’t we all ari https://t.co/15W...
15916    RT @puppywang18: 7 or nothing\n#MAMAVOTE #GOT7...
17862    RT @KushbooMadam: Feel the Pleasure\n💟💟💟💟💟💟💟\n...
15231    RT @lollipollipop: According to this news, EXO...
18076    RT @cafe_army: JIN's Cherished Items\n\n"Used ...
18329    RT @RenukaJain6: I am broken today emotionally...
17923    RT @jaeminpic: [STATION 3] YERI x RENJUN x JEN...
Name: text, Length: 4963, dtype: object

In [197]:
df1['user']

4115     8.011630e+05
16712    1.182851e+06
2171     3.241081e+06
1763     6.020572e+06
10032    6.870172e+06
7472     7.485052e+06
3640     7.703052e+06
9049     1.131958e+07
15178    1.334294e+07
8275     1.339020e+07
16204    1.445053e+07
988      1.465380e+07
5198     1.470811e+07
10636    1.473965e+07
622      1.516226e+07
14640    1.519101e+07
4572     1.519940e+07
5420     1.520581e+07
3401     1.522577e+07
4597     1.530124e+07
1786     1.562349e+07
3919     1.582448e+07
12336    1.604394e+07
8147     1.626108e+07
7376     1.633101e+07
15335    1.636770e+07
9358     1.652790e+07
352      1.671184e+07
6187     1.692586e+07
17705    1.738357e+07
             ...
6456     1.072365e+18
1602     1.072400e+18
2200     1.072410e+18
15606    1.072421e+18
15851    1.072426e+18
10141    1.072432e+18
10416    1.072486e+18
10966    1.072490e+18
15493    1.072543e+18
6467     1.072565e+18
16786    1.072573e+18
6003     1.072587e+18
12359    1.072615e+18
8589     1.072705e+18
7846     1.072732e+18
12884    1.072774e+18
2325     1.072779e+18
3324     1.072785e+18
16100    1.072785e+18
5803     1.072789e+18
13321    1.072797e+18
6687     1.072798e+18
14125    1.072799e+18
14128    1.072800e+18
15916    1.072801e+18
17862    1.072802e+18
15231    1.072802e+18
18076    1.072803e+18
18329    1.072803e+18
17923    1.072804e+18
Name: user, Length: 4963, dtype: float64

In [207]:
uid = 8.011630e+05
c = 0
unique_ids = [uid]
lst_at = [0]
lst_links = [0]
lst_hash = [0]
for index,row in df1.iterrows():
    if (row['user'] == uid):
        lst_at[c] = lst_at[c] + (str)(row['text']).count('@')
        lst_links[c] = lst_links[c] + (str)(row['text']).count('https:') 
        lst_hash[c] = lst_hash[c] + (str)(row['text']).count('#')
           
    else:
       lst_at.append(row['text'].count('@'))
       lst_links.append((str)(row['text']).count('http:') )
       lst_hash.append(row['text'].count('#'))
       uid = row['user']
       unique_ids.append(uid)
       c = c + 1

In [208]:
len(lst_hash)

4831

In [209]:
len(lst_links)

4831

In [210]:
len(unique_ids)

4831

In [211]:
final_df2 = pd.DataFrame(
    {'user_id': unique_ids,
     'count of tweets with @': lst_at,
     'count of tweets with links': lst_links,
     'count of tweets with hashtags': lst_hash
    })

In [212]:
final_df2.head()

,user_id,count of tweets with @,count of tweets with links,count of tweets with hashtags
0,801163.0,1,1,0
1,1182851.0,1,0,0
2,3241081.0,0,0,0
3,6020572.0,2,0,3
4,6870172.0,2,0,0

In [214]:
df= pd.merge(final_df2, final_df, on='user_id', how='inner')

In [215]:
df.head()

,user_id,count of tweets with @,count of tweets with links,count of tweets with hashtags,reputation of user
0,801163.0,1,1,0,0.425595
1,1182851.0,1,0,0,0.361780
2,3241081.0,0,0,0,0.632197
3,6020572.0,2,0,3,0.966525
4,6870172.0,2,0,0,0.606225

In [317]:
df.to_csv('live_content_based_features.csv')

# Extracting emozi information

In [217]:
df1['id']

4115     1.072799e+18
16712    1.072800e+18
2171     1.072799e+18
1763     1.072799e+18
10032    1.072799e+18
7472     1.072799e+18
3640     1.072799e+18
9049     1.072799e+18
15178    1.072800e+18
8275     1.072799e+18
16204    1.072800e+18
988      1.072799e+18
5198     1.072799e+18
10636    1.072799e+18
622      1.072798e+18
14640    1.072800e+18
4572     1.072799e+18
5420     1.072799e+18
3401     1.072799e+18
4597     1.072799e+18
1786     1.072799e+18
3919     1.072799e+18
12336    1.072799e+18
8147     1.072799e+18
7376     1.072799e+18
15335    1.072800e+18
9358     1.072799e+18
352      1.072798e+18
6187     1.072799e+18
17705    1.072800e+18
             ...
6456     1.072799e+18
1602     1.072799e+18
2200     1.072799e+18
15606    1.072800e+18
15851    1.072800e+18
10141    1.072799e+18
10416    1.072799e+18
10966    1.072799e+18
15493    1.072800e+18
6467     1.072799e+18
16786    1.072800e+18
6003     1.072799e+18
12359    1.072799e+18
8589     1.072799e+18
7846     1.072799e+18
12884    1.072799e+18
2325     1.072799e+18
3324     1.072799e+18
16100    1.072800e+18
5803     1.072799e+18
13321    1.072800e+18
6687     1.072799e+18
14125    1.072800e+18
14128    1.072800e+18
15916    1.072800e+18
17862    1.072800e+18
15231    1.072800e+18
18076    1.072800e+18
18329    1.072800e+18
17923    1.072800e+18
Name: id, Length: 4963, dtype: float64

In [270]:
emozi_map = {'😁':0.9,'😂':0.99,'😃':0.89,'😄': 0.85,
'😆':0.7,'😉': 0.6,'😊':0.7,
'😍': 0.84,'😘':0.88,'😚':0.78,
'😐':0.5,'😥':0.4,
'😫':0.3,'😌': 0.6,'😜': 0.57,'😲':0.4,'😖':0.1,'😤': 0.2,'😢':0.5,'😭': 0.1,'😨': 0.3,'😩':0.35,'😰':0.32,'😱':0.25,
'😡':0.75,'😠':0.14,'👿':0.75,'😺':0.7,'😹':0.75,'😻':0.6,'😽':0.68,'🙀':0.3,'🙈':0.56,'🙉':0.56,'🙊':0.56,'👍':0.99,
'👍':0.01,'💔':0.1,'💕':0.8,'💞':0.76,'🔥':0.6}

In [271]:
emozi_des_map = {'😁':'Grinning Face With Smiling Eyes','😂':'Face With Tears of Joy',
'😃':'Grinning Face With Big Eyes','😄':'Smiling Face With Open Mouth and Smiling Eyes',
'😆':'Smiling Face With Open Mouth and Tightly-Closed Eyes','😉':'Winking Face',
'😊':'Smiling Face With Smiling Eyes',
'😍': 'Smiling Face With Heart-Eyes','😘':'Face Throwing a Kiss',
'😚':'Kissing Face With Closed Eye',
'😐':'Neutral Face','😥':'Disappointed but Relieved Face',
'😫':'Tired Face','😌': 'Relieved Face','😜':'Face With Stuck-Out Tongue and Winking Eye',
'😲':'Astonished Face','😖':'Confounded Face','😤':'Face With Look of Triumph','😢':'Crying Face5',
'😭': 'Loudly Crying Face'
,'😨': 'Fearful Face','😩':'Weary Face','😰':'Face With Open Mouth and Cold Sweat','😱':'Face Screaming in Fear',
'😡':'Pouting Face','😠':'Angry Face','👿':'Angry Face With Horns','😺':'Smiling Cat Face With Open Mout',
'😹':'Cat Face With Tears of Joy','😻':'Smiling Cat Face With Heart-Shaped Eyes',
'😽':'Kissing Cat Face With Closed Eyes','🙀':'Weary Cat Face'
,'🙈':'See-No-Evil Monkey','🙉':'Hear-No-Evil Monke','🙊':'Speak-No-Evil Monkey','👍':'Thumbs Up Sign',
'👎':'Thumbs Down Sign','💔':'Broken Heart','💕':'Two Hearts','💞':'Revolving Hearts','🔥':'Fire emozi'}

In [302]:
def CountFrequency(l1,s1): 
    freq = {} 
    sc = {}
    summ=0
    if(len(l1)==0):
        return 0
    for i in range(len(l1)): 
        item = l1[i]
        if (item in freq): 
            freq[item] += 1
            summ=summ+s1[i]
        else: 
            freq[item] = 1
            sc[item] = s1[i]
            summ=summ+s1[i];
    
    avg=summ/len(l1)
    
    
    for key, value in freq.items():
        if(value>=2 and value<=10 and sc[key]>0):
            avg=min(1,avg+0.1)
        elif(value>10 and sc[key]>0):
            avg=min(1,avg+0.2)
        elif(value>=2 and value<=10 and sc[key]<0):
            avg=max(-1,avg-0.1)
        elif(value>10 and sc[key]>0):
            avg=max(-1,avg-0.2)
        
    return avg

In [303]:
emozi = []
emozi_des = []
emozi_sc = []
agg_sc = []
c = 0 
for index,row in df1.iterrows():
    emozi.append(0)
    emozi_des.append([])
    emozi_sc.append([])
    for x in str(row['text']):
        if(x in emozi_map):
            
            emozi_des[c].append( emozi_des_map[x])
            
            emozi_sc[c].append(emozi_map[x])
            
            emozi[c]=emozi[c] + 1
    agg_sc.append(CountFrequency(emozi_des[c],emozi_sc[c]))
    c = c + 1

In [305]:
ids = list(df1['user'])
twt_id = list(df1['id'])
twt = list(df1['text'])

emozi_df = pd.DataFrame(
    {'user_id':ids ,
     'tweet id': twt_id,
     'tweet':twt ,
     'emozi_count': emozi ,
     'emozi_description':emozi_des,
     'emozi_scores': emozi_sc,
     'aggregated_score': agg_sc
    })

In [306]:
emozi_df.head()

,user_id,tweet id,tweet,emozi_count,emozi_description,emozi_scores,aggregated_score
0,801163.0,1.072799e+18,RT @J1HOON: i see no difference https://t.co/i...,0,[],[],0.00
1,1182851.0,1.072800e+18,RT @btsdanisharmy: The boys doing their thing ...,2,"[Face With Tears of Joy, Face With Tears of Joy]","[0.99, 0.99]",1.00
2,3241081.0,1.072799e+18,Media Speaks: Flag off (Hausla Cancer Awarenes...,0,[],[],0.00
3,6020572.0,1.072799e+18,RT @Taepics95: 🐯: “and we’ll dance very... ver...,0,[],[],0.00
4,6870172.0,1.072799e+18,RT @Harem_sa: If you sharing a birthday with t...,1,[Smiling Face With Heart-Eyes],[0.84],0.84

In [307]:
emozi_df=emozi_df[emozi_df['emozi_count']>0]

In [308]:
emozi_df.head(10)

,user_id,tweet id,tweet,emozi_count,emozi_description,emozi_scores,aggregated_score
1,1182851.0,1.072800e+18,RT @btsdanisharmy: The boys doing their thing ...,2,"[Face With Tears of Joy, Face With Tears of Joy]","[0.99, 0.99]",1.00
4,6870172.0,1.072799e+18,RT @Harem_sa: If you sharing a birthday with t...,1,[Smiling Face With Heart-Eyes],[0.84],0.84
11,14653803.0,1.072799e+18,RT @ErlianaShofia: Wanna one 😍\n#MAMAVOTE #wa...,1,[Smiling Face With Heart-Eyes],[0.84],0.84
14,15162264.0,1.072798e+18,RT @jeonggukpics: Jungkook you are just illega...,1,[Smiling Face With Heart-Eyes],[0.84],0.84
22,16043942.0,1.072799e+18,RT @1K_Younginn: Internet Capp 🔥Drop Or Not ? ...,1,[Fire emozi],[0.6],0.60
29,17383566.0,1.072800e+18,RT @prince__danik: THIS COVER IS SO 🔥🔥🔥🔥\n\n😭😭...,8,"[Fire emozi, Fire emozi, Fire emozi, Fire emoz...","[0.6, 0.6, 0.6, 0.6, 0.1, 0.1, 0.1, 0.1]",0.55
32,17720465.0,1.072799e+18,And there's a twist here.... Watch the video n...,1,[Face With Tears of Joy],[0.99],0.99
34,18185282.0,1.072799e+18,RT @BTSARMY_Salon: #MAMAVOTE #BTS @BTS_twt Let...,7,"[Fire emozi, Fire emozi, Fire emozi, Fire emoz...","[0.6, 0.6, 0.6, 0.6, 0.6, 0.6, 0.6]",0.70
45,18940422.0,1.072798e+18,RT @MTV: Have you ever seen anything cuter????...,1,[Two Hearts],[0.8],0.80
57,19970375.0,1.072799e+18,RT @kittieieie: I love JAPAN 😭 https://t.co/Vx...,1,[Loudly Crying Face],[0.1],0.10

In [316]:
emozi_df.to_csv('emozi_features.csv')